### See https://github.com/lindell/multi-gitter#config-file for all options

# The maximum number of concurrent runs.
concurrent: 1

branch: jenkins-version-2.361-to-2.375

# What should happen if the branch already exist.
# Available values:
#   skip: Skip making any changes to the existing branch and do not create a new pull request.
#   replace: Replace the existing content of the branch by force pushing any new changes, then reuse any existing pull request, or create a new one if none exist.
conflict-strategy: replace

# Comment this out if you don't have permissions on the repository
labels:
 - dependencies

# The level of logging that should be made. Available values: trace, debug, info, error.
log-level: info

# Fork the repository instead of creating a new branch on the same owner.
### Needed to operate on repositories where you don't have enought permissions
fork: true

# If set, make the fork to the defined value. Default behavior is for the fork to be on the logged in user.
### Set to a test organisation to not polute your GitHub profile with many forks
# fork-owner: timja-bot

commit-message: Upgrade the Jenkins baseline from 2.361.x to 2.375.x
pr-body: |
  _This is an autogenerated PR for updating the Jenkins baseline._

  2.361.x is subject to [seven](https://www.jenkins.io/security/advisory/2023-03-08/) security vulnerabilities coming from Jenkins itself, and has been removed from the Jenkins BOM. 

  Ping @NotMyFault if any questions.

  _[script source](https://github.com/NotMyFault/jenkins-version-updater)_
# # # The name, including owner of a GitHub repository in the format "ownerName/repoName".
repo:
  - jenkinsci/junit-plugin
# #   - mylittlecorp/jenkins-infra-test-plugin
# #   - lemeurherve/jenkins-infra-test-plugin
#   - jenkinsci/jenkins-infra-test-plugin
# # #   - jenkinsci/test-results-aggregator-plugin

# # The name of a GitHub organization. All repositories in that organization will be used.
# org:
#   - jenkinsci


# Skip changes on specified repositories, the name is including the owner of repository in the format "ownerName/repoName".
skip-repo: []
