### See https://github.com/lindell/multi-gitter#config-file for all options

# The maximum number of concurrent runs.
concurrent: 1

branch: replace-deprecated-hamcrest-modules

# What should happen if the branch already exist.
# Available values:
#   skip: Skip making any changes to the existing branch and do not create a new pull request.
#   replace: Replace the existing content of the branch by force pushing any new changes, then reuse any existing pull request, or create a new one if none exist.
conflict-strategy: replace

# Comment this out if you don't have permissions on the repository
labels:
 - dependencies

# The level of logging that should be made. Available values: trace, debug, info, error.
log-level: info

# Fork the repository instead of creating a new branch on the same owner.
### Needed to operate on repositories where you don't have enough permissions
fork: true

commit-message: Replace deprecated 'hamcrest-*' modules with 'hamcrest'
pr-body: |
  _🤖 This is an automatic PR for replacing the deprecated 'hamcrest-*' modules with 'hamcrest'._

  All deprecated modules' code has been merged into 'hamcrest'.
  Consumers of `hamcrest-*` should replace the dependency with `hamcrest`, which is the drop-in module containing the code of the deprecated `hamcrest-*` modules.

  Ping `@NotMyFault` if you have questions.

  _[script source](https://github.com/NotMyFault/jenkins-version-updater)_
# # # The name, including owner of a GitHub repository in the format "ownerName/repoName".
repo:
  - jenkinsci/console-column-plugin

# Skip changes on specified repositories, the name is including the owner of repository in the format "ownerName/repoName".
skip-repo: []
